name: xpx_chain_sdk
version: 0.0.3+1
description: Official ProximaX Sirius Blockchain SDK Library in Dart.
author: "Eleazar Garrido <eleazar.garrido@proximax.io>"
homepage: https://www.proximax.io

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flat_buffers: '^1.11.0'
  http: '^0.11.3+17'
  base32: '^1.0.1'
  fixnum: '^0.10.9'
  xpx_crypto: '^0.0.1'
  convert: '^2.1.1'

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
