name: xpx_catapult_sdk
version: 0.0.1
description: Official ProximaX Sirius Blockchain SDK Library in Dart

environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  http: '>=0.11.1 <0.12.0'
  base32: '>=1.0.1 <2.0.0'
  fixnum: '^0.10.9'
  nem2_crypto: ^1.0.3
dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
